#pragma once

// Device IDs
#define VANTTEC_CAN_ID_JETSON 0x01
#define VANTTEC_CAN_ID_STEPPER_RX 0x08

// Message IDs
#define VANTTEC_CAN_ID_ESTOP 0x00
#define VANTTEC_CAN_ID_HB 0x01
#define VANTTEC_CAN_ID_DRIVE_MODE 0x02
#define VANTTEC_CAN_ID_DRIVER_PRESENT 0x03
#define VANTTEC_CAN_ID_REVERSE 0x04
#define VANTTEC_CAN_ID_PEDAL_BRAKE 0x05
#define VANTTEC_CAN_ID_DRIVER_FAULT 0x06

#define VANTTEC_CAN_ID_STEERING 0x10
#define VANTTEC_CAN_ID_BRAKING 0x11

#define VANTTEC_CAN_ID_DEBUG 0xFA
