/*
 * requirements.h
 *
 *  Created on: May 22, 2023
 *      Author: Z0180064
 */

#ifndef PLATFORM_SPECIFIC_VANTTEC_CANLIB_STM_GENERIC_TASKS_REQUIREMENTS_H_
#define PLATFORM_SPECIFIC_VANTTEC_CANLIB_STM_GENERIC_TASKS_REQUIREMENTS_H_

void init_requirements_task();

#endif /* PLATFORM_SPECIFIC_VANTTEC_CANLIB_STM_GENERIC_TASKS_REQUIREMENTS_H_ */
